/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Accounting Location Api
 * Accounting Location API defining how to get and modify Accounting Locations
 * OpenAPI spec version: 0.1.0
 */

export type AccountingLocationStatus = typeof AccountingLocationStatus[keyof typeof AccountingLocationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountingLocationStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
