/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Pouch Management Service
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */

export interface AdditionalItems {
  itemID: string;
  pouchBarcode?: string;
  materialType?: string;
  currencyCode?: string;
  denominationValue?: number;
  valueInPence: number;
  valueRevaluated?: number;
  quantity: number;
  weight?: number;
}
