/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * place holder if any filed required in future, to be used a key/value pair in tokens object if token name is prepended with *, then it will be treated as personal data
 */
export type AdditionalItemTokens = { [key: string]: any };
