/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * cash_drawer_association
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */

/**
 * association data
 */
export interface AssociationDto {
  entityType: string;
  entityID: string;
  operationType: string;
}
