/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Accounting Location Api
 * Accounting Location API defining how to get and modify Accounting Locations
 * OpenAPI spec version: 0.1.0
 */
import type { CounterID } from './counterID';
import type { AccountingLocationID } from './accountingLocationID';
import type { UpdatedBy } from './updatedBy';

export interface Association {
  counterID: CounterID;
  counterName: string;
  cashDrawerID: AccountingLocationID;
  cashDrawerName: string;
  updatedBy?: UpdatedBy;
}
