/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { BackofficePouchValue } from './backofficePouchValue';

export interface BackofficePouchEditHistory {
  pouch_type_name?: string;
  assigned_branch_id?: string;
  assigned_branch_name?: string;
  status?: string;
  total_pouch_value?: number;
  pouch_bag_type?: string;
  is_branch_close?: boolean;
  is_coin_pouch?: boolean;
  date?: number;
  date_of_preparation?: number;
  preparation_txn_id?: string;
  pouch_barcode?: string;
  prepared_smart_id?: string;
  prepared_user_id?: string;
  pouch_id?: string;
  pouch_type?: string;
  prepared_branch_id?: string;
  prepared_branch_name?: string;
  suspend_count?: number;
  denomination_ladder?: BackofficePouchValue[];
}
