/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type BasketClosedBasketState = typeof BasketClosedBasketState[keyof typeof BasketClosedBasketState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketClosedBasketState = {
  BKC: 'BKC',
} as const;
