/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { BasketClosedBasketState } from './basketClosedBasketState';
import type { BasketClosedFulfilmentState } from './basketClosedFulfilmentState';

/**
 * used to close basket in put method of basket resource.
 */
export interface BasketClosed {
  /** concatenation of FADcode (7 characters), nodeID (between 33 and 64) and basket Sequence Number provided by device */
  basketID: string;
  basketState: BasketClosedBasketState;
  NumberOfEntries: number;
  fulfilmentState?: BasketClosedFulfilmentState;
}
