/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { BasketCreateResponseFulfilmentType } from './basketCreateResponseFulfilmentType';

export interface BasketCreateResponse {
  fulfilmentType?: BasketCreateResponseFulfilmentType;
  fulfilmentRequired?: boolean;
}
