/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type BasketCreateResponseFulfilmentType = typeof BasketCreateResponseFulfilmentType[keyof typeof BasketCreateResponseFulfilmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketCreateResponseFulfilmentType = {
  Payzone: 'Payzone',
  None: 'None',
} as const;
