/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type BasketCoreFulfilmentState = typeof BasketCoreFulfilmentState[keyof typeof BasketCoreFulfilmentState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketCoreFulfilmentState = {
  success: 'success',
  failure: 'failure',
  pending: 'pending',
  notRequired: 'notRequired',
} as const;
