/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { BasketCore } from './basketCore';

/**
 * Used to store basket information in database. This is also returned in get basket method
 */
export interface Basket {
  basketCore: BasketCore;
  basketOpenedBy?: string;
  basketClosedBy?: string;
  organizationCode?: string;
  organizationCodeVersion: string;
  deviceType: string;
  deviceID: string;
  basketSeqNum: number;
  nodeID: string;
  fadCode: string;
  BasketCreatedTime?: number;
  BasketClosedTime?: number;
}
