/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { Basket } from './basket';
import type { Entry } from './entry';

/**
 * Used to store basket information in database. This is also returned in get basket method
 */
export interface BasketWithEntries {
  basket: Basket;
  entries: Entry[];
}
