/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type BasketCoreBasketState = typeof BasketCoreBasketState[keyof typeof BasketCoreBasketState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BasketCoreBasketState = {
  BKC: 'BKC',
  BKO: 'BKO',
} as const;
