/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */

/**
 * branch data
 */
export interface BranchDetails {
  branch_addres?: string;
  branch_name?: string;
  branch_type?: string;
  fadcode?: string;
}
