/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { ItemDetails } from './itemDetails';
import type { ActionList } from './actionList';

/**
 * Cash Drawer details
 */
export interface CashDrawerData {
  associated_counter_terminal: string;
  associated_counter_terminal_id: string;
  smart_id: string;
  user_name: string;
  entity: string;
  entity_id: string;
  branch_id: string;
  entity_name: string;
  sequence_no: number;
  operation_type: string;
  flow_type: string;
  entity_type: string;
  item_details: ItemDetails;
  action_list: ActionList[];
}
