/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Accounting Location Api
 * Accounting Location API defining how to get and modify Accounting Locations
 * OpenAPI spec version: 0.1.0
 */

/**
 * Return all counter association when 0 and exclude the counter association from when counter ID is provided.
 */
export type CounterIDParamParameter = string;
