/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */
import type { PouchID } from './pouchID';
import type { PouchType } from './pouchType';
import type { PouchSubType } from './pouchSubType';
import type { TotalValue } from './totalValue';
import type { Items } from './items';

export type CreatePouchBodyBody = {
  pouchID: PouchID;
  pouchType: PouchType;
  pouchSubType?: PouchSubType;
  totalValue?: TotalValue;
  items: Items;
};
