/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { ParcelsData } from './parcelsData';

/**
 * Despatchable Items
 */
export interface DespatchableData {
  branchId?: string;
  counterId?: string;
  clerkId?: string;
  parcels: ParcelsData[];
}
