/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { CashDrawerData } from './cashDrawerData';
import type { ReasonCode } from './reasonCode';

export interface DiscrepencyData {
  entity?: CashDrawerData;
  reason?: ReasonCode;
  comments?: string;
  discrepency_date_time?: number;
  status: string;
  discrepency_data_ID?: string;
}
