/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { CashDrawerData } from './cashDrawerData';
import type { ReasonCode } from './reasonCode';

export interface DiscrepencyDetails {
  variance_balance?: number;
  date_time?: number;
  status?: string;
  entity?: CashDrawerData;
  reason?: ReasonCode;
  comments?: string;
}
