/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * <credence>To show when transactions have been keyed after the event, i.e. In fall back mode
 */
export type EntryCoreFallBackModeFlag = typeof EntryCoreFallBackModeFlag[keyof typeof EntryCoreFallBackModeFlag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryCoreFallBackModeFlag = {
  Y: 'Y',
  N: 'N',
} as const;
