/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * <Credence>The transmission source for the transaction.
PG = Post & Go
PS = Paystation 
SPZ = Payzone SPM
HX = Horizon
CA = Camelot
 */
export type EntryTransmissionSource = typeof EntryTransmissionSource[keyof typeof EntryTransmissionSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryTransmissionSource = {
  PG: 'PG',
  PS: 'PS',
  PZ: 'PZ',
  HX: 'HX',
  CA: 'CA',
  SPZ: 'SPZ',
} as const;
