/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { EntryCoreTokens } from './entryCoreTokens';
import type { AdditionalItem } from './additionalItem';
import type { EntryCoreReversalIndicator } from './entryCoreReversalIndicator';
import type { EntryCoreRefundFlag } from './entryCoreRefundFlag';
import type { EntryCoreFallBackModeFlag } from './entryCoreFallBackModeFlag';

/**
 * used to capture basket entry information, used in post method of basket entry

 */
export interface EntryCore {
  transactionStartTime: number;
  itemID: string;
  itemDescription?: string;
  itemType?: string;
  quantity: number;
  entryID: number;
  valueInPence: number;
  /** @deprecated */
  value?: number;
  receiptLine?: string;
  /** Placeholder for key values field we may require  if token name is prepended with *, then it will be treated as personal data */
  tokens?: EntryCoreTokens;
  additionalItems?: AdditionalItem[];
  /** <credence>Unique identifier to distinguish between all stock units within each branch */
  stockunitIdentifier?: string;
  /** <credence>How each transaction is captured at the point of sale
RDS maintained – Values: 
0 = Barcode
1 = Keyboard/Screen (Manual)
2 = Magnetic Card
3 = Smart Card
4 = Fallback to Mag Swipe (Horizon) or Smart Key (PayStation)
5 = Scales
9 = Kiosk (Post & Go Only)
 */
  methodOfDataCapture?: number;
  /** To show if reversals have taken place 
Default ‘0’ ; ‘1’ shows that this is a linked reversed transaction; ‘2’ shows that this is a non linked reversed transaction */
  reversalIndicator?: EntryCoreReversalIndicator;
  /** <credence>To show when refunds have been provided
 */
  refundFlag?: EntryCoreRefundFlag;
  /** <credence>To show when transactions have been keyed after the event, i.e. In fall back mode */
  fallBackModeFlag?: EntryCoreFallBackModeFlag;
  /** <credence>Bar Code can Reference.  Only applicable to External Transaction Types */
  bcsReference?: string;
  /** <CFS>Transaction Reference 

Pouch Identifier

Transaction Correction Reference

Transaction Acknowledgment Reference

For Transaction Acknowledgements. This field contains the TA Reference Number.

NOTE: Assumed to be in scope for the completion of this document. Later phase design changes may alter this and subject to understanding of E2E process for TC’s and TA’s, may be remove */
  accountReferenceID?: string;
  /** <CFS>Client Reference number (supplied by client).
This will only be used for the actioned Transactions Correction being passed back to POL SAP against the client products.  

Usage to be controlled via reference data */
  clientReference?: string;
}
