/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * Placeholder for key values field we may require  if token name is prepended with *, then it will be treated as personal data
 */
export type EntryCoreTokens = { [key: string]: any };
