/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * <credence>To show when refunds have been provided

 */
export type EntryCoreRefundFlag = typeof EntryCoreRefundFlag[keyof typeof EntryCoreRefundFlag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryCoreRefundFlag = {
  N: 'N',
  Y: 'Y',
} as const;
