/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type EntryResponseFulfilmentType = typeof EntryResponseFulfilmentType[keyof typeof EntryResponseFulfilmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryResponseFulfilmentType = {
  Remote: 'Remote',
  PED: 'PED',
  None: 'None',
  label: 'label',
} as const;
