/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

/**
 * To show if reversals have taken place 
Default ‘0’ ; ‘1’ shows that this is a linked reversed transaction; ‘2’ shows that this is a non linked reversed transaction
 */
export type EntryCoreReversalIndicator = typeof EntryCoreReversalIndicator[keyof typeof EntryCoreReversalIndicator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryCoreReversalIndicator = {
  NUMBER_1: 1,
  NUMBER_0: 0,
  NUMBER_2: 2,
} as const;
