/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { EntryCore } from './entryCore';
import type { Fulfilment } from './fulfilment';
import type { EntryTransmissionSource } from './entryTransmissionSource';

/**
 * Entry model used to store information in database
 */
export interface Entry {
  entryID?: string;
  RequestUDID?: string;
  entryCore?: EntryCore;
  fulfilmentType?: string;
  fulfilment?: Fulfilment;
  transactionEndTime?: number;
  basketID?: string;
  fadCode?: string;
  entryUpdatedBy?: string;
  organizationCode?: string;
  organizationCodeVersion?: string;
  deviceType?: string;
  deviceID?: string;
  nodeID?: string;
  basketSeqNum?: number;
  /** <Credence>The transmission source for the transaction.
PG = Post & Go
PS = Paystation 
SPZ = Payzone SPM
HX = Horizon
CA = Camelot */
  transmissionSource?: EntryTransmissionSource;
}
