/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */
import type { FulfilmentFulfilmentState } from './fulfilmentFulfilmentState';
import type { FulfilmentFulfilmentTokens } from './fulfilmentFulfilmentTokens';

export interface Fulfilment {
  fulfilmentState: FulfilmentFulfilmentState;
  fulfilmentTokens?: FulfilmentFulfilmentTokens;
}
