/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type FulfilmentFulfilmentState = typeof FulfilmentFulfilmentState[keyof typeof FulfilmentFulfilmentState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FulfilmentFulfilmentState = {
  success: 'success',
  failure: 'failure',
  indeterminate: 'indeterminate',
  pending: 'pending',
  notRequired: 'notRequired',
} as const;
