/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Accounting Location Api
 * Accounting Location API defining how to get and modify Accounting Locations
 * OpenAPI spec version: 0.1.0
 */
import type { StatusParamParameter } from './statusParamParameter';

export type GetAccountingLocationParams = {
/**
 * Filter by status (e.g. "active")
 */
status?: StatusParamParameter;
};
