/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * cash_drawer_association
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */

export type GetOnboardedDataParams = { branch_id: string; entity_type: string };
