/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */
import type { FromDateParamParameter } from './fromDateParamParameter';
import type { ToDateParamParameter } from './toDateParamParameter';
import type { LastEvaluatedKeyParameter } from './lastEvaluatedKeyParameter';

export type GetPouchHistoryParams = {
/**
 * From Date as a unix timestamp in seconds
 */
fromDate?: FromDateParamParameter;
/**
 * To Date as a unix timestamp in seconds
 */
toDate?: ToDateParamParameter;
/**
 * Passed to DynamoDB to get the next set of paginated results
 */
lastEvaluatedKey?: LastEvaluatedKeyParameter;
};
