/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */

/**
 * Item level details
 */
export interface ItemDetails {
  /** last balanced unixtimestamp for the entity */
  last_balanced_date_time: number;
  current_variance: number;
  to_date_variance: number;
  last_balance: number;
  transfer_amt: number;
  transfer_amt_date: number;
}
