/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */

/**
 * Items Data
 */
export interface ItemDTO {
  id?: string;
  name?: string;
  type?: string;
  weight?: string;
  price?: number;
  quantity?: number;
  total?: number;
}
