/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */

/**
 * Passed to DynamoDB to get the next set of paginated results
 */
export type LastEvaluatedKeyParameter = string;
