/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export interface LastseqnumberResponse {
  branchID: string;
  nodeID: number;
  lastSeqNumber: number;
}
