/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { SubMenu } from './subMenu';

/**
 * Menu
 */
export interface Menu {
  id: string;
  title: string;
  icon: string;
  link: string;
  sub_menu: SubMenu[];
}
