/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * cash_drawer_association
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */

/**
 * onboarded data
 */
export interface OnboardingData {
  createdBy?: string;
  entity?: string;
  entityID?: string;
  entityType?: string;
  fadcode?: string;
  operationType?: string;
}
