/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */

/**
 * Parcel Data
 */
export interface ParcelsData {
  trackingId: string;
  carrierId: string;
  serviceName: string;
  afterLastDespatch?: boolean;
  acceptanceDate?: number;
  addressLine1?: string;
  country?: string;
  daysBeforeExpiry?: number;
  postcode?: string;
  preventCustomerPickup?: boolean;
  status?: string;
}
