/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Pouch Management Service
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */
import type { AdditionalItems } from './additionalItems';

/**
 * Validate Pouch Available for Despatch,
 */
export interface PouchValidationForPreparedPouches {
  additionalItems: AdditionalItems[];
  assignedBranchID: string;
  assignedBranchName: string;
  pouchBarcode: string;
  pouchID?: string;
  valueInPence: number;
  pouchType?: string;
  transactionID?: string;
  userName: string;
  itemID: string;
}
