/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */
import type { AssignedBranchID } from './assignedBranchID';
import type { AssignedBranchName } from './assignedBranchName';
import type { PouchID } from './pouchID';
import type { PouchType } from './pouchType';
import type { PouchSubType } from './pouchSubType';
import type { PouchDespatchStatus } from './pouchDespatchStatus';
import type { TotalValue } from './totalValue';
import type { TransactionID } from './transactionID';
import type { ItemID } from './itemID';
import type { UpdatedBy } from './updatedBy';
import type { PouchDataForDespatchItems } from './pouchDataForDespatchItems';

export interface PouchDataForDespatch {
  assignedBranchID?: AssignedBranchID;
  assignedBranchName?: AssignedBranchName;
  pouchID: PouchID;
  pouchType: PouchType;
  pouchSubType?: PouchSubType;
  status: PouchDespatchStatus;
  totalValue?: TotalValue;
  transactionID: TransactionID;
  itemID: ItemID;
  updatedBy: UpdatedBy;
  items: PouchDataForDespatchItems;
}
