/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */

export type PouchSubType = typeof PouchSubType[keyof typeof PouchSubType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PouchSubType = {
  useable_notes: 'useable_notes',
  non_useable_notes: 'non_useable_notes',
  non_useable_coins: 'non_useable_coins',
  useable_coins_full_bag: 'useable_coins_full_bag',
  useable_coins_part_bag: 'useable_coins_part_bag',
} as const;
