/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */

export type PouchType = typeof PouchType[keyof typeof PouchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PouchType = {
  cash: 'cash',
  stock: 'stock',
} as const;
