/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */
import type { AssignedBranchID } from "./assignedBranchID";
import type { AssignedBranchName } from "./assignedBranchName";
import type { DeliveredBranchID } from "./deliveredBranchID";
import type { IsBranchValid } from "./isBranchValid";
import type { IsPouchValid } from "./isPouchValid";
import type { IsPouchValueAssociated } from "./isPouchValueAssociated";
import type { PouchID } from "./pouchID";
import type { PouchType } from "./pouchType";
import type { PouchAcceptanceStatus } from "./pouchAcceptanceStatus";
import type { TotalValue } from "./totalValue";
import type { TransactionID } from "./transactionID";
import type { ItemID } from "./itemID";
import type { UpdatedBy } from "./updatedBy";
import type { PouchAcceptanceDetailsItems } from "./pouchAcceptanceDetailsItems";

export interface PouchAcceptanceDetails {
  assignedBranchID?: AssignedBranchID;
  assignedBranchName?: AssignedBranchName;
  deliveredBranchID?: DeliveredBranchID;
  isBranchValid: IsBranchValid;
  isPouchValid: IsPouchValid;
  isPouchValueAssociated: IsPouchValueAssociated;
  pouchID: PouchID;
  pouchType: PouchType;
  status: PouchAcceptanceStatus;
  totalValue?: TotalValue;
  transactionID: TransactionID;
  itemID?: ItemID;
  updatedBy: UpdatedBy;
  items: PouchAcceptanceDetailsItems;
}
