/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { PouchDataDTO } from './pouchDataDTO';

/**
 * pouch data
 */
export interface PouchApiResponse {
  is_suspended_pouch: boolean;
  suspended_by: string;
  pouch_details: PouchDataDTO[];
}
