/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { SubReasonCode } from './subReasonCode';

/**
 * reason-code
 */
export interface ReasonCode {
  id?: string;
  title?: string;
  code?: string;
  sub_reason?: SubReasonCode;
}
