/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */
import type { ReceiptPreviewDTO } from './receiptPreviewDTO';

/**
 * Receipt Data
 */
export interface ReceiptDTO {
  id?: string;
  transaction_amount?: number;
  branch_id?: string;
  receipt_preview?: ReceiptPreviewDTO;
  date_time?: number;
  counter_terminal_id?: string;
}
