/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type ReversalReversalStatus = typeof ReversalReversalStatus[keyof typeof ReversalReversalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReversalReversalStatus = {
  NotReversed: 'NotReversed',
  Reversed: 'Reversed',
} as const;
