/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * BBO Pouch Management Api
 * Replaces `pouch-management-api` Pouch Management API defining how to get and modify Pouch data
 * OpenAPI spec version: 0.1.0
 */

export type StatusParamParameterItem = typeof StatusParamParameterItem[keyof typeof StatusParamParameterItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusParamParameterItem = {
  prepared: 'prepared',
  cancelled: 'cancelled',
  suspended: 'suspended',
  despatched: 'despatched',
  accepted: 'accepted',
} as const;
