/**
 * Generated by orval v6.7.1 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions

PO Counter Terminal

PO Counter Terminal

PO Counter Terminal

PO Branch Management
 * OpenAPI spec version: 0.1.0
 */

/**
 * Task details
 */
export interface TaskData {
  task: string;
  level: string;
  trigger: string;
  run_date_time: number;
  completion_date_time: number;
  branch_id: string;
  user: string;
  status: string;
  entity_id: string;
  entity: string;
  role: string;
  task_id: string;
  task_type: string;
  entity_name: string;
}
