/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * transactionsViewer
 * PO Transactions Viewer
 * OpenAPI spec version: 0.1.0
 */
import type { TransactionTokens } from './transactionTokens';

export interface Transaction {
  fadCode?: string;
  nodeID?: string;
  deviceID?: string;
  deviceType?: string;
  basketID?: string;
  BasketCreatedTime?: number;
  basketOpenedBy?: string;
  entryID?: string;
  entryUpdatedBy?: string;
  BasketClosedTime?: number;
  basketClosedBy?: string;
  TransactionID?: string;
  TransactionMode?: number;
  TransactionStartTime?: number;
  itemID?: string;
  itemDescription?: string;
  quantity?: number;
  valueInPence?: number;
  Tokens?: TransactionTokens;
  TransactionEndTime?: number;
}
