/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * transactionsViewer
 * PO Transactions Viewer
 * OpenAPI spec version: 0.1.0
 */
import type { Transaction } from './transaction';

export interface Transactions {
  Transactions?: Transaction[];
}
