/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Transfer Transactions
 * PO Transactions
 * OpenAPI spec version: 0.1.0
 */

/**
 * Placeholder for key values field we may require
 */
export type TransferCoreTokens = { [key: string]: any };
