/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * transactionsViewer
 * PO Transactions Viewer
 * OpenAPI spec version: 0.1.0
 */

export type TransactionTokens = {[key: string]: string};
