/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * transactions
 * PO Transactions
 * OpenAPI spec version: 0.3.0
 */

export type UpdateBasketEntryFulfilmentBodyTwo = { [key: string]: any };
