/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Pouch Management Service
 * PO Counter Terminal
 * OpenAPI spec version: 0.1.0
 */

export type ValidatePreparedPouchesParams = { transactionID?: string; barcode: string };
