export enum QUERY_KEYS {
  VALIDATE_POUCH = "VALIDATE_POUCH",
  VALIDATE_POUCH_ACCACCEPTANCE = "VALIDATE_POUCH_ACCACCEPTANCE",
  AVAILABLE_POUCH_FOR_ACCACCEPTANCE = "AVAILABLE_POUCH_FOR_ACCACCEPTANCE",
  VALIDATE_ACC_CARD = "VALIDATE_ACC_CARD",
  COUNTERS_LIST = "COUNTERS_LIST",
  RECEIPT_LIST = "RECEIPT_LIST",
}
