export enum SCREENS {
  LOGIN = "/login",
  HOME = "/home",
  CASH_DRAWER = "/cash-drawer",
  CASH_TRANSFER = "/cash-transfer",
  POUCH_ACCEPTANCE = "/pouch-acceptance",
  RECEIPT = "/receipt",
  POUCH_DESPATCH = "/pouch-despatch",
  PMS_MODULE = "/pms-module",
  SELF_REGISTER = "/self-register",
  SYSTEM_INFO = "/system-info",
  LICENCE_INFO = "/licence-info",
  ENVIRONMENT_VARIABLE_CONFIG = "/environment-variable-config",
  FEATURE_FLAG_CONFIG = "/feature-flag-config",
  AUTH_REDIRECT = "/auth-redirect",
  SIGNOUT_REDIRECT = "/signout-redirect",
  USER_LOGIN = "/user-login",
  NOT_ALLOWED_ON_THIS_BRANCH = "not-allowed-on-this-branch",
}
