export const STATE_CONSTANTS = {
  FULFILLED_AND_CALCULATED: "fulfilledAndCalculated",
  FULFILLMENT_SUCCESS: "success",
  FULFILLMENT_FAILED: "failure",
  FULFILLMENT_PENDING: "pending",
  FULFILLMENT_INDETERMINATE: "indeterminate",
  FULFILLMENT_NOT_INITIATED: "fulfillmentNotInitiated",
  FULFILLMENT_INITIATED: "fulfillmentInitiated",
  FULFILLMENT_NOT_REQUIRED: "notRequired",
  NOTINITIATED: "notInitiated",
  FAILED: "failed",
  SUCCESS: "success",
  SKIPPED: "skipped",
  FAIL: "fail",
  COMMIT_INITIATED: "commitInitiated",
  STAGE_HOME: "home",
  STAGE_TENDERING: "tendering",
  STAGE_REPAY: "repay",
  STAGE_REFUND: "refund",
  STAGE_COMPLETED: "completed",
  CASH: "cash",
  CARD: "card",
  CHEQUE: "cheque",
  CASH_TENDER_RECEIVED_AMOUNT: "cashTenderReceivedAmount",
  CASH_TENDER_TENDERED_AMOUNT: "cashTenderTenderedAmount",
  CARD_PAYMENT: "Card Payment",
  IDLE_TIMEOUT: 1000 * 60 * 15,
} as const;
