import { CommitStatus } from "@ct/common/state/HomeScreen/updateBasket.slice";
import { IbasketItem } from "@ct/interfaces/basket.interface";

export const basketItemMock = (): IbasketItem[] => {
  const data = [
    {
      name: "Balance Enquiry Test",
      id: "Balance Enquiry Test100dd975-8a11-476d-a135-b5a84ec07168",
      item: ["Balance Enquiry Test"],
      quantity: 1,
      total: 0,
      voidable: true,
      journeyData: {
        basket: { id: "Balance Enquiry Test" },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          entryID: 1,
          itemID: "50211",
          quantity: 1,
          quantityFixed: "true",
          receiptLine: "1",
          tokens: {
            agentSlaInfo: "TBC",
            amountRequested: "0",
            authorisation_code: "WILL_COME_FROM_FULFILLMENT",
            bankResponse: "WILL_COME_FROM_FULFILLMENT",
            bankTransactionID: "WILL_COME_FROM_FULFILLMENT",
            bankValueFlag: "N",
            cardImpounded: "0",
            clientID: "1234",
            counterSlaInfo: "TBC",
            currency: "GBP",
            entryID: "1",
            fee: "0",
            financialTransaction: "TBC",
            fulfilmentAction: "balance",
            horizonTransactionID: "TBC",
            issuerSchemeID: "1234",
            merchantNumber: "TBC",
            pan: "1234",
            receiptDate: "20220719",
            recoveryFlag: "N",
            responseCode: "WILL_COME_FROM_FULFILLMENT",
            routingGateway: "TBC",
            settlementDate: "20220719",
            transactionResultCode: "WILL_COME_FROM_FULFILLMENT",
            transactionType: "TBC",
          },
          transactionStartTime: 1661783875553,
          valueInPence: 0,
          voidable: "true",
          uniqueID: "100dd975-8a11-476d-a135-b5a84ec07168",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 0,
    },
    {
      name: "Global Priority Ret: EU344961022GB",
      id: "Global Priority Ret: EU344961022GBfcb2402a-cd27-473a-8cdd-9c50ec91a337",
      item: ["Global Priority Ret: EU344961022GB"],
      quantity: 1,
      total: 0,
      voidable: true,
      journeyData: {
        basket: {
          "Reference No": "EU344961022GB",
          Service: "Global Priority Ret",
          afterLastCollection: "false",
          duplicateBarcodeIdentifier: "EU344961022GB",
          id: "Global Priority Ret: EU344961022GB",
          journeyCompatibilityTag: "customer_facing",
          repDespatch: "true",
        },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          additionalItems: [{ itemID: "38072", valueInPence: 0, quantity: 1 }],
          entryType: "mails",
          itemID: "39192",
          quantity: 1,
          receiptLine: "1",
          tokens: {
            APTransactionReference: "0001",
            Dest: " ",
            SenderAddress: "London UK",
            SenderName: "Hildenborough",
            SenderPostcode: "123453",
            TandTCarrier: "POLP",
            TandTSvcID: "DPR",
            TandTType: "D",
            UPUTrackingNumber: "EU344961022GB",
            addressValidated: "0",
            afterLastDespatch: "false",
            barcode: "EU344961022GB",
            carrier: "PF",
            clientAccountNo: "3131",
            clientSrvCode: "1",
            compensationValue: " ",
            conditionAccepted: " ",
            consequentialLossBand: " ",
            copIssued: "0",
            copprn: " ",
            country: "GB",
            customerRefNumber: "EU344961022GB",
            destination: " ",
            destinationAddress: " ",
            destinationAreaId: " ",
            firstAddressLine: " ",
            isFranked: "0",
            paymentCode: "1",
            pipFormat: "Default",
            prePaidLine: "1",
            prepaidAmount: "0",
            prn: " ",
            receiptReference: "unknown",
            serviceId: "92",
            serviceName: "Global Priority Ret",
            tokenIdentifier: "9635",
            town: " ",
            versionNumber: "1",
            weight: " ",
          },
          transactionStartTime: 1661784459525,
          valueInPence: 0,
          uniqueID: "fcb2402a-cd27-473a-8cdd-9c50ec91a337",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 0,
    },
    {
      name: "Cash Withdrawal:EU344961022GB",
      id: "Cash Withdrawal:EU344961022GBfcb2402a-cd27-473a-8cdd-9c50ec91a337",
      item: ["Cash Withdrawal:EU344961022GB"],
      quantity: 1,
      total: 100,
      voidable: true,
      journeyData: {
        basket: {
          ReferenceNo: "EU344961022GB",
          Service: "GlobalPriorityRet",
          afterLastCollection: "false",
          duplicateBarcodeIdentifier: "EU344961022GB",
          id: "Cash Withdrawal:EU344961022GB",
          journeyCompatibilityTag: "customer_facing",
          repDespatch: "true",
        },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          additionalItems: [
            {
              itemID: "38072",
              valueInPence: 0,
              quantity: 1,
            },
          ],
          entryType: "mails",
          itemID: "39192",
          quantity: 1,
          receiptLine: "1",
          tokens: {
            APTransactionReference: "0001",
            Dest: "",
            SenderAddress: "LondonUK",
            SenderName: "Hildenborough",
            SenderPostcode: "123453",
            TandTCarrier: "POLP",
            TandTSvcID: "DPR",
            TandTType: "D",
            UPUTrackingNumber: "EU344961022GB",
            addressValidated: "0",
            afterLastDespatch: "false",
            barcode: "EU344961022GB",
            carrier: "PF",
            clientAccountNo: "3131",
            clientSrvCode: "1",
            compensationValue: "",
            conditionAccepted: "",
            consequentialLossBand: "",
            copIssued: "0",
            copprn: "",
            country: "GB",
            customerRefNumber: "EU344961022GB",
            destination: "",
            destinationAddress: "",
            destinationAreaId: "",
            firstAddressLine: "",
            isFranked: "0",
            paymentCode: "1",
            pipFormat: "Default",
            prePaidLine: "1",
            prepaidAmount: "0",
            prn: "",
            receiptReference: "unknown",
            serviceId: "92",
            serviceName: "GlobalPriorityRet",
            tokenIdentifier: "9635",
            town: "",
            versionNumber: "1",
            weight: "",
          },
          transactionStartTime: 1661784459525,
          valueInPence: 10000,
          uniqueID: "fcb2402a-cd27-473a-8cdd-9c50ec91a337",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 100,
    },
  ] as unknown as IbasketItem[];

  return data;
};

export const basketItemMockForRefund = (): IbasketItem[] => {
  const data = [
    {
      name: "Balance Enquiry Test",
      id: "Balance Enquiry Test100dd975-8a11-476d-a135-b5a84ec07168",
      item: ["Balance Enquiry Test"],
      quantity: -1,
      total: 0,
      voidable: true,
      journeyData: {
        basket: { id: "Balance Enquiry Test" },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          entryID: 1,
          itemID: "50211",
          quantity: -1,
          journeyType: "refund",
          quantityFixed: "true",
          receiptLine: "1",
          tokens: {
            agentSlaInfo: "TBC",
            amountRequested: "0",
            authorisation_code: "WILL_COME_FROM_FULFILLMENT",
            bankResponse: "WILL_COME_FROM_FULFILLMENT",
            bankTransactionID: "WILL_COME_FROM_FULFILLMENT",
            bankValueFlag: "N",
            cardImpounded: "0",
            clientID: "1234",
            counterSlaInfo: "TBC",
            currency: "GBP",
            entryID: "1",
            fee: "0",
            financialTransaction: "TBC",
            fulfilmentAction: "balance",
            horizonTransactionID: "TBC",
            issuerSchemeID: "1234",
            merchantNumber: "TBC",
            pan: "1234",
            receiptDate: "20220719",
            recoveryFlag: "N",
            responseCode: "WILL_COME_FROM_FULFILLMENT",
            routingGateway: "TBC",
            settlementDate: "20220719",
            transactionResultCode: "WILL_COME_FROM_FULFILLMENT",
            transactionType: "TBC",
          },
          transactionStartTime: 1661783875553,
          valueInPence: -10,
          voidable: "true",
          uniqueID: "100dd975-8a11-476d-a135-b5a84ec07168",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 0,
    },
    {
      name: "Global Priority Ret: EU344961022GB",
      id: "Global Priority Ret: EU344961022GBfcb2402a-cd27-473a-8cdd-9c50ec91a337",
      item: ["Global Priority Ret: EU344961022GB"],
      quantity: 1,
      total: 0,
      voidable: true,
      journeyData: {
        basket: {
          "Reference No": "EU344961022GB",
          Service: "Global Priority Ret",
          afterLastCollection: "false",
          duplicateBarcodeIdentifier: "EU344961022GB",
          id: "Global Priority Ret: EU344961022GB",
          journeyCompatibilityTag: "customer_facing",
          repDespatch: "true",
        },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          additionalItems: [{ itemID: "38072", valueInPence: 0, quantity: 1 }],
          entryType: "mails",
          itemID: "39192",
          quantity: -1,
          journeyType: "refund",
          receiptLine: "1",
          tokens: {
            APTransactionReference: "0001",
            Dest: " ",
            SenderAddress: "London UK",
            SenderName: "Hildenborough",
            SenderPostcode: "123453",
            TandTCarrier: "POLP",
            TandTSvcID: "DPR",
            TandTType: "D",
            UPUTrackingNumber: "EU344961022GB",
            addressValidated: "0",
            afterLastDespatch: "false",
            barcode: "EU344961022GB",
            carrier: "PF",
            clientAccountNo: "3131",
            clientSrvCode: "1",
            compensationValue: " ",
            conditionAccepted: " ",
            consequentialLossBand: " ",
            copIssued: "0",
            copprn: " ",
            country: "GB",
            customerRefNumber: "EU344961022GB",
            destination: " ",
            destinationAddress: " ",
            destinationAreaId: " ",
            firstAddressLine: " ",
            isFranked: "0",
            paymentCode: "1",
            pipFormat: "Default",
            prePaidLine: "1",
            prepaidAmount: "0",
            prn: " ",
            receiptReference: "unknown",
            serviceId: "92",
            serviceName: "Global Priority Ret",
            tokenIdentifier: "9635",
            town: " ",
            versionNumber: "1",
            weight: " ",
          },
          transactionStartTime: 1661784459525,
          valueInPence: -10,
          uniqueID: "fcb2402a-cd27-473a-8cdd-9c50ec91a337",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 0,
    },
    {
      name: "Cash Withdrawal:EU344961022GB",
      id: "Cash Withdrawal:EU344961022GBfcb2402a-cd27-473a-8cdd-9c50ec91a337",
      item: ["Cash Withdrawal:EU344961022GB"],
      quantity: -1,
      total: 100,
      voidable: true,
      journeyData: {
        basket: {
          ReferenceNo: "EU344961022GB",
          Service: "GlobalPriorityRet",
          afterLastCollection: "false",
          duplicateBarcodeIdentifier: "EU344961022GB",
          id: "Cash Withdrawal:EU344961022GB",
          journeyCompatibilityTag: "customer_facing",
          repDespatch: "true",
        },
        transaction: {
          commitAndFulfillPoint: "aggregated",
          additionalItems: [
            {
              itemID: "38072",
              valueInPence: 0,
              quantity: 1,
            },
          ],
          entryType: "mails",
          itemID: "39192",
          journeyType: "refund",
          quantity: -1,
          receiptLine: "1",
          tokens: {
            APTransactionReference: "0001",
            Dest: "",
            SenderAddress: "LondonUK",
            SenderName: "Hildenborough",
            SenderPostcode: "123453",
            TandTCarrier: "POLP",
            TandTSvcID: "DPR",
            TandTType: "D",
            UPUTrackingNumber: "EU344961022GB",
            addressValidated: "0",
            afterLastDespatch: "false",
            barcode: "EU344961022GB",
            carrier: "PF",
            clientAccountNo: "3131",
            clientSrvCode: "1",
            compensationValue: "",
            conditionAccepted: "",
            consequentialLossBand: "",
            copIssued: "0",
            copprn: "",
            country: "GB",
            customerRefNumber: "EU344961022GB",
            destination: "",
            destinationAddress: "",
            destinationAreaId: "",
            firstAddressLine: "",
            isFranked: "0",
            paymentCode: "1",
            pipFormat: "Default",
            prePaidLine: "1",
            prepaidAmount: "0",
            prn: "",
            receiptReference: "unknown",
            serviceId: "92",
            serviceName: "GlobalPriorityRet",
            tokenIdentifier: "9635",
            town: "",
            versionNumber: "1",
            weight: "",
          },
          transactionStartTime: 1661784459525,
          valueInPence: 10000,
          uniqueID: "fcb2402a-cd27-473a-8cdd-9c50ec91a337",
        },
      },
      commitStatus: CommitStatus.notInitiated,
      price: 100,
    },
  ] as unknown as IbasketItem[];

  return data;
};

export const commitAndFulfillPointBeforePaymentWithValueFlagMock = (): IbasketItem => {
  return {
    name: "CommitAndFulfillPoint BeforePayment With Value Flag Mock",
    id: "CommitAndFulfillPoint BeforePayment With Value Flag Mock100dd975-8a11-476d-a135-b5a84ec07168",
    item: ["CommitAndFulfillPoint BeforePayment With Value Flag Mock"],
    quantity: 1,
    total: 100,
    voidable: true,
    journeyData: {
      basket: { id: "CommitAndFulfillPoint BeforePayment With Value Flag Mock" },
      transaction: {
        commitAndFulfillPoint: "beforePayment",
        itemID: "50211",
        quantity: 1,
        quantityFixed: "true",
        receiptLine: "1",
        tokens: {
          agentSlaInfo: "TBC",
          amountRequested: "0",
          authorisation_code: "WILL_COME_FROM_FULFILLMENT",
          bankResponse: "WILL_COME_FROM_FULFILLMENT",
          bankTransactionID: "WILL_COME_FROM_FULFILLMENT",
          bankValueFlag: "N",
          cardImpounded: "0",
          clientID: "1234",
          counterSlaInfo: "TBC",
          currency: "GBP",
          entryID: "1",
          fee: "0",
          financialTransaction: "TBC",
          fulfilmentAction: "balance",
          horizonTransactionID: "TBC",
          issuerSchemeID: "1234",
          merchantNumber: "TBC",
          pan: "1234",
          receiptDate: "20220719",
          recoveryFlag: "N",
          responseCode: "WILL_COME_FROM_FULFILLMENT",
          routingGateway: "TBC",
          settlementDate: "20220719",
          transactionResultCode: "WILL_COME_FROM_FULFILLMENT",
          transactionType: "TBC",
        },
        transactionStartTime: 1661783875553,
        valueInPence: 10000,
        voidable: "true",
        uniqueID: "100dd975-8a11-476d-a135-b5a84ec07168",
      },
    },
    commitStatus: CommitStatus.notInitiated,
    price: 100,
  } as unknown as IbasketItem;
};

export const chequePayloadMock: IbasketItem = {
  price: 0,
  id: "cheque332f830b-c93b-4953-b23c-50c702dedffb",
  name: "Cheque",
  total: -32.5,
  deductAmount: true,
  commitStatus: CommitStatus.notInitiated,
  fulFillmentStatus: "fulfillmentNotInitiated",
  quantity: 0,
  additionalItemsValue: 0,
  source: "local",
  localUUID: "332f830b-c93b-4953-b23c-50c702dedffb",
};
