export const rdcPouchListForAcceptance = [
  {
    assignedBranchID: "1098683",
    assignedBranchName: "Cambusbarron",
    status: "ToBeAccepted",
    totalPouchValue: 0,
    currencyCode: "GBP",
    containerTypeCode: 60,
    date: 20221024,
    pouchBarcode: "360770922163",
    type: 3,
    ContentInMaterials: {
      denominationLadder: [
        {
          itemID: 657,
          materialReferenceCode: 657,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 1000,
          valueInPence: 200000,
          valueRevaluated: 200000,
          quantity: 200,
          weight: 144,
        },
        {
          itemID: 658,
          materialReferenceCode: 658,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 500,
          valueInPence: 50000,
          valueRevaluated: 50000,
          quantity: 100,
          weight: 68,
        },
      ],
    },
    cashCenterCode: "D33",
    finalCITDepotCode: "RM",
    masterRouteCode: "RM1MX1",
    masterRouteWeekDay: 1,
    suspendCount: 0,
    preparedBranchID: "433",
  },
  {
    assignedBranchID: "1098683",
    assignedBranchName: "Cambusbarron",
    status: "ToBeAccepted",
    totalPouchValue: 0,
    currencyCode: "GBP",
    containerTypeCode: 60,
    date: 20221024,
    pouchBarcode: "360770922156",
    type: 3,
    ContentInMaterials: {
      denominationLadder: [
        {
          itemID: 656,
          materialReferenceCode: 656,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 2000,
          valueInPence: 200000,
          valueRevaluated: 200000,
          quantity: 100,
          weight: 81,
        },
        {
          itemID: 658,
          materialReferenceCode: 658,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 500,
          valueInPence: 50000,
          valueRevaluated: 50000,
          quantity: 100,
          weight: 68,
        },
      ],
    },
    cashCenterCode: "D33",
    finalCITDepotCode: "RM",
    masterRouteCode: "RM1MX1",
    masterRouteWeekDay: 1,
    suspendCount: 0,
    preparedBranchID: "433",
  },
  {
    assignedBranchID: "1098683",
    assignedBranchName: "Cambusbarron",
    status: "ToBeAccepted",
    totalPouchValue: 0,
    currencyCode: "GBP",
    containerTypeCode: 60,
    date: 20221024,
    pouchBarcode: "360770922149",
    type: 3,
    ContentInMaterials: {
      denominationLadder: [
        {
          itemID: 656,
          materialReferenceCode: 656,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 2000,
          valueInPence: 200000,
          valueRevaluated: 200000,
          quantity: 100,
          weight: 81,
        },
        {
          itemID: 658,
          materialReferenceCode: 658,
          materialType: "NOTE",
          currencyCode: "GBP",
          denomination: 500,
          valueInPence: 50000,
          valueRevaluated: 50000,
          quantity: 100,
          weight: 68,
        },
      ],
    },
    cashCenterCode: "D33",
    finalCITDepotCode: "RM",
    masterRouteCode: "RM1MX1",
    masterRouteWeekDay: 1,
    suspendCount: 0,
    preparedBranchID: "433",
  },
];
